import { Product, CategoryMeta } from '@/types';

export const CATEGORIES: CategoryMeta[] = [
  { id: 'all', label: 'All', labelHi: 'सभी', emoji: '🛍️' },
  { id: 'fashion', label: 'Fashion', labelHi: 'फैशन', emoji: '👕' },
  { id: 'footwear', label: 'Footwear', labelHi: 'जूते-चप्पल', emoji: '👟' },
  { id: 'bags', label: 'Bags', labelHi: 'बैग', emoji: '👜' },
  { id: 'home', label: 'Home', labelHi: 'घर', emoji: '🏠' },
  { id: 'kitchen', label: 'Kitchen & Steel', labelHi: 'किचन', emoji: '🍽️' },
  { id: 'plastic', label: 'Plastic Items', labelHi: 'प्लास्टिक', emoji: '🧴' },
];

export const MOCK_PRODUCTS: Product[] = [
  // Fashion
  {
    id: 'f1',
    name: "Men's Casual Shirt",
    nameHi: 'पुरुषों की कैजुअल शर्ट',
    price: 299,
    description: 'Stylish daily wear shirt, comfortable cotton fabric',
    descriptionHi: 'स्टाइलिश डेली वियर शर्ट, आरामदायक कॉटन कपड़ा',
    category: 'fashion',
    emoji: '👔',
    inStock: true,
    badge: 'Bestseller',
  },
  {
    id: 'f2',
    name: "Men's Denim Jeans",
    nameHi: 'पुरुषों की डेनिम जींस',
    price: 499,
    description: 'Style aur durability ka perfect combo – daily wear jeans',
    descriptionHi: 'स्टाइल और मजबूती का परफेक्ट कॉम्बो – डेली वियर जींस',
    category: 'fashion',
    emoji: '👖',
    inStock: true,
  },
  {
    id: 'f3',
    name: "Women's Kurti",
    nameHi: 'महिलाओं की कुर्ती',
    price: 249,
    description: 'Elegant kurti for casual & festive look',
    descriptionHi: 'कैजुअल और फेस्टिव लुक के लिए एलिगेंट कुर्ती',
    category: 'fashion',
    emoji: '👗',
    inStock: true,
    badge: 'New',
  },
  {
    id: 'f4',
    name: "Ladies Top",
    nameHi: 'लेडीज़ टॉप',
    price: 199,
    description: 'Trendy top with soft fabric and modern design',
    descriptionHi: 'सॉफ्ट फैब्रिक और मॉडर्न डिज़ाइन के साथ ट्रेंडी टॉप',
    category: 'fashion',
    emoji: '👚',
    inStock: true,
  },
  {
    id: 'f5',
    name: 'Kids Printed T-Shirt',
    nameHi: 'बच्चों की प्रिंटेड टी-शर्ट',
    price: 149,
    description: 'Cute and colorful t-shirt for kids',
    descriptionHi: 'बच्चों के लिए क्यूट और रंगीन टी-शर्ट',
    category: 'fashion',
    emoji: '👕',
    inStock: true,
  },
  // Footwear
  {
    id: 'fw1',
    name: 'Sports Shoes',
    nameHi: 'स्पोर्ट्स शूज़',
    price: 399,
    description: 'Comfortable shoes for daily use & walking',
    descriptionHi: 'डेली यूज़ और वॉकिंग के लिए आरामदायक जूते',
    category: 'footwear',
    emoji: '👟',
    inStock: true,
    badge: 'Popular',
  },
  {
    id: 'fw2',
    name: "Men's Slippers",
    nameHi: 'पुरुषों की चप्पलें',
    price: 149,
    description: 'Lightweight and durable daily wear slippers',
    descriptionHi: 'हल्की और मजबूत डेली वियर चप्पलें',
    category: 'footwear',
    emoji: '🩴',
    inStock: true,
  },
  {
    id: 'fw3',
    name: "Ladies Sandal",
    nameHi: 'लेडीज़ सैंडल',
    price: 199,
    description: 'Stylish sandal perfect for casual outings',
    descriptionHi: 'कैजुअल आउटिंग के लिए स्टाइलिश सैंडल',
    category: 'footwear',
    emoji: '👡',
    inStock: true,
  },
  // Bags
  {
    id: 'b1',
    name: 'School Bag',
    nameHi: 'स्कूल बैग',
    price: 299,
    description: 'Strong and spacious bag for students',
    descriptionHi: 'छात्रों के लिए मजबूत और विशाल बैग',
    category: 'bags',
    emoji: '🎒',
    inStock: true,
  },
  {
    id: 'b2',
    name: 'Travel Bag',
    nameHi: 'ट्रैवल बैग',
    price: 499,
    description: 'Durable bag for short trips & travel',
    descriptionHi: 'छोटी यात्राओं के लिए टिकाऊ बैग',
    category: 'bags',
    emoji: '🧳',
    inStock: true,
    badge: 'New',
  },
  {
    id: 'b3',
    name: "Ladies Purse",
    nameHi: 'लेडीज़ पर्स',
    price: 199,
    description: 'Compact and stylish purse for daily use',
    descriptionHi: 'डेली यूज़ के लिए कॉम्पैक्ट और स्टाइलिश पर्स',
    category: 'bags',
    emoji: '👜',
    inStock: true,
  },
  // Home
  {
    id: 'h1',
    name: 'Electric Kettle',
    nameHi: 'इलेक्ट्रिक केतली',
    price: 599,
    description: 'Quick boiling kettle for tea & coffee',
    descriptionHi: 'चाय और कॉफी के लिए जल्दी उबालने वाली केतली',
    category: 'home',
    emoji: '⚡',
    inStock: true,
    badge: 'Hot Deal',
  },
  {
    id: 'h2',
    name: 'LED Bulb (9W)',
    nameHi: 'LED बल्ब (9W)',
    price: 99,
    description: 'Energy-saving bright light bulb',
    descriptionHi: 'ऊर्जा बचाने वाला चमकीला बल्ब',
    category: 'home',
    emoji: '💡',
    inStock: true,
  },
  // Kitchen
  {
    id: 'k1',
    name: 'Steel Plate Set',
    nameHi: 'स्टील प्लेट सेट',
    price: 299,
    description: 'Strong stainless steel plates for daily use',
    descriptionHi: 'डेली यूज़ के लिए मजबूत स्टेनलेस स्टील प्लेट',
    category: 'kitchen',
    emoji: '🍽️',
    inStock: true,
  },
  {
    id: 'k2',
    name: 'Steel Glass (Set of 2)',
    nameHi: 'स्टील गिलास (2 का सेट)',
    price: 149,
    description: 'Durable and rust-free steel glasses',
    descriptionHi: 'टिकाऊ और जंग-मुक्त स्टील गिलास',
    category: 'kitchen',
    emoji: '🥛',
    inStock: true,
  },
  {
    id: 'k3',
    name: 'Cooking Pan',
    nameHi: 'कुकिंग पैन',
    price: 399,
    description: 'Non-stick pan for easy cooking',
    descriptionHi: 'आसान खाना पकाने के लिए नॉन-स्टिक पैन',
    category: 'kitchen',
    emoji: '🍳',
    inStock: true,
    badge: 'Bestseller',
  },
  // Plastic
  {
    id: 'p1',
    name: 'Plastic Storage Container',
    nameHi: 'प्लास्टिक स्टोरेज कंटेनर',
    price: 199,
    description: 'Useful for storing kitchen items',
    descriptionHi: 'किचन आइटम स्टोर करने के लिए उपयोगी',
    category: 'plastic',
    emoji: '📦',
    inStock: true,
  },
  {
    id: 'p2',
    name: 'Water Bottle (1L)',
    nameHi: 'वाटर बोतल (1L)',
    price: 99,
    description: 'Leak-proof and easy to carry',
    descriptionHi: 'लीक-प्रूफ और आसानी से ले जाने योग्य',
    category: 'plastic',
    emoji: '🧴',
    inStock: true,
  },
  {
    id: 'p3',
    name: 'Laundry Basket',
    nameHi: 'लॉन्ड्री बास्केट',
    price: 249,
    description: 'Strong plastic basket for clothes',
    descriptionHi: 'कपड़ों के लिए मजबूत प्लास्टिक बास्केट',
    category: 'plastic',
    emoji: '🧺',
    inStock: true,
  },
  {
    id: 'p4',
    name: 'Bucket & Mug Set',
    nameHi: 'बाल्टी और मग सेट',
    price: 199,
    description: 'Durable bathroom utility set',
    descriptionHi: 'टिकाऊ बाथरूम यूटिलिटी सेट',
    category: 'plastic',
    emoji: '🪣',
    inStock: true,
  },
];
